# LangSmith
LANGSMITH_TRACING: "true"
LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
LANGSMITH_API_KEY: <YOUR_API_KEY>
LANGSMITH_PROJECT: <YOUR_PROJECT_NAME>

# ChatGPT
OPENAI_API_KEY: <YOUR_API_KEY>